# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Figure.create(name: "Bob Barker", birth_date: "December 12, 1923", death_date: "still living", hometown: "Darrington, Washington", profession: "Game Show Host", gender: "M", bio: "Barker spent most of his youth on the Rosebud Indian Reservation in South Dakota. His mother was a school teacher; his father was the foreman on the electrical high line through the state of Washington. In 1931, the family moved to Springfield, Missouri, where Barker graduated from Central High School in 1941. Barker attended Drury College (now Drury University) in Springfield, on a basketball scholarship. He was a member of the Epsilon Beta Chapter of Sigma Nu fraternity at Drury. On the outbreak of World War II, Barker served in the United States Navy as a fighter pilot. After the war, he returned to Drury to finish his education, graduating summa cum laude with a degree in economics.")

Figure.create(name: "Brad Pitt", birth_date: "December 18, 1963", death_date: "still living", hometown: "Shawnee, Oklahoma", profession: "Actor", gender: "M", bio: "Pitt was born to William Alvin Pitt, who ran a trucking company, and Jane Etta (née Hillhouse), a school counsellor. The family soon moved to Springfield, Missouri, where he lived together with his younger siblings, Douglas and Julie Neal. He was raised as Southern Baptist, but has since stated that he does not 'have a great relationship with religion'. Pitt has described Springfield as 'Mark Twain country, Jesse James country', having grown up with 'a lot of hills, a lot of lakes'. Pitt attended Kickapoo High School, where he was a member of the golf, swimming and tennis teams.He participated in the school's Key and Forensics clubs, in school debates, and in musicals. Following his graduation from high school, Pitt enrolled in the University of Missouri in 1982, majoring in journalism with a focus on advertising. As graduation approached, Pitt did not feel ready to settle down. He loved films and, since films were not made in Missouri, he decided to go to where they were made.Two weeks before earning his degree, Pitt left the university and moved to Los Angeles, where he took acting lessons and worked odd jobs.")
